// rw_config.cpp — RaidWatch settings loader (T4). See rw_config.hpp.
//
// rapidyaml single-header convention: in exactly one translation unit, define
// RYML_SINGLE_HDR_DEFINE_NOW and include ryml_all.hpp before any other use;
// this emits the non-inline definitions. Do NOT include ryml_all.hpp anywhere
// else.

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "../../../third_party/ryml_all.hpp"

#include "rw_config.hpp"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace raidwatch {
namespace {

namespace fs = std::filesystem;
namespace ry = ryml;

// ---------------------------------------------------------------- helpers ---

[[nodiscard]] std::string str(ry::csubstr s) { return {s.data(), s.size()}; }

// Emit a warning to stderr (the TUI/service has no logger yet) and optionally
// record it for the caller's testability.
void warn(std::vector<std::string>* sink, const std::string& msg) {
    std::fprintf(stderr, "[rw_config] WARNING: %s\n", msg.c_str());
    if (sink) sink->push_back(msg);
}

bool operator_is_valid(const std::string& op) {
    for (const char* v : kValidOperators)
        if (op == v) return true;
    return false;
}

bool severity_is_valid(const std::string& sev) {
    for (const char* v : kValidSeverities)
        if (sev == v) return true;
    return false;
}

// --- scalar coercion (throw on type mismatch — real config mistakes) -------

[[nodiscard]] bool to_bool(ry::csubstr s, const std::string& ctx) {
    auto v = str(s);
    if (v == "true" || v == "True" || v == "TRUE" || v == "yes") return true;
    if (v == "false" || v == "False" || v == "FALSE" || v == "no") return false;
    throw RwConfigError(ctx + ": expected bool, got '" + v + "'");
}

[[nodiscard]] long long to_int(ry::csubstr s, const std::string& ctx) {
    auto v = str(s);
    // ryml may mark ints; we still parse defensively.
    try {
        size_t pos = 0;
        long long out = std::stoll(v, &pos);
        if (pos != v.size()) throw 0;
        return out;
    } catch (...) {
        throw RwConfigError(ctx + ": expected integer, got '" + v + "'");
    }
}

[[nodiscard]] double to_double(ry::csubstr s, const std::string& ctx) {
    auto v = str(s);
    try {
        size_t pos = 0;
        double out = std::stod(v, &pos);
        if (pos != v.size()) throw 0;
        return out;
    } catch (...) {
        throw RwConfigError(ctx + ": expected number, got '" + v + "'");
    }
}


// ----------------------------------------------------------------- dump -----

// Quote a string scalar for YAML output. Always double-quoted (simplest way to
// be correct for Windows paths, regex, free text); escape backslash + quote.
std::string yq(const std::string& v) {
    std::string out;
    out.reserve(v.size() + 2);
    out += '"';
    for (char c : v) {
        if (c == '\\' || c == '"') out += '\\';
        out += c;
    }
    out += '"';
    return out;
}

}  // namespace

// ------------------------------------------------------------- dump impl ----

std::string dump_config_yaml(const RwConfig& cfg) {
    std::ostringstream o;
    o << "# Auto-generated by raidwatch (no config.yaml.example present).\n";
    o << "processes:\n";
    o << "  spt_server_process_name: " << yq(cfg.processes.spt_server_process_name) << "\n";
    o << "  headless_process_name: " << yq(cfg.processes.headless_process_name) << "\n";
    o << "  headless_cmdline_pattern: " << yq(cfg.processes.headless_cmdline_pattern) << "\n";

    o << "collection:\n";
    o << "  interval_seconds: " << cfg.collection.interval_seconds << "\n";
    o << "  history_retention_hours: " << cfg.collection.history_retention_hours << "\n";
    o << "  whea_poll_seconds: " << cfg.collection.whea_poll_seconds << "\n";
    o << "  top_others_poll_seconds: " << cfg.collection.top_others_poll_seconds << "\n";

    o << "temps:\n";
    o << "  lhm_dll_path: " << yq(cfg.temps.lhm_dll_path) << "\n";
    o << "  cpu_sensor_name: " << yq(cfg.temps.cpu_sensor_name) << "\n";
    o << "  tctl_offset: " << cfg.temps.tctl_offset << "\n";

    o << "fika:\n";
    o << "  spt_path: " << yq(cfg.fika.spt_path) << "\n";
    o << "  raid_udp_port: " << cfg.fika.raid_udp_port << "\n";
    o << "  headless_path: " << yq(cfg.fika.headless_path) << "\n";
    if (cfg.fika.log_paths.empty()) {
        o << "  log_paths: {}\n";
    } else {
        o << "  log_paths:\n";
        for (const auto& [k, v] : cfg.fika.log_paths) o << "    " << k << ": " << yq(v) << "\n";
    }
    if (cfg.fika.risky_mod_names.empty()) {
        o << "  risky_mod_names: []\n";
    } else {
        o << "  risky_mod_names:\n";
        for (const auto& m : cfg.fika.risky_mod_names) o << "    - " << yq(m) << "\n";
    }

    if (cfg.gates.empty()) {
        o << "gates: {}\n";
    } else {
        o << "gates:\n";
        for (const auto& [id, g] : cfg.gates) {
            o << "  " << id << ":\n";
            o << "    enabled: " << (g.enabled ? "true" : "false") << "\n";
            o << "    threshold: " << g.threshold << "\n";
            o << "    operator: " << yq(g.op) << "\n";
            o << "    duration_seconds: " << g.duration_seconds << "\n";
            o << "    severity: " << yq(g.severity) << "\n";
            o << "    recommendation: " << yq(g.recommendation) << "\n";
            o << "    metric: " << yq(g.metric) << "\n";
        }
    }
    return o.str();
}

namespace {

// ------------------------------------------------------- section parsers ----

void parse_processes(ry::ConstNodeRef& n, RwConfig& cfg,
                     std::vector<std::string>* unk) {
    for (auto f : n.children()) {
        auto k = str(f.key());
        if (k == "spt_server_process_name") cfg.processes.spt_server_process_name = str(f.val());
        else if (k == "headless_process_name") cfg.processes.headless_process_name = str(f.val());
        else if (k == "headless_cmdline_pattern") cfg.processes.headless_cmdline_pattern = str(f.val());
        else warn(unk, "unknown key under 'processes': " + k);
    }
}

void parse_collection(ry::ConstNodeRef& n, RwConfig& cfg,
                      std::vector<std::string>* unk) {
    for (auto f : n.children()) {
        auto k = str(f.key());
        if (k == "interval_seconds") cfg.collection.interval_seconds = to_double(f.val(), "collection.interval_seconds");
        else if (k == "history_retention_hours") cfg.collection.history_retention_hours = static_cast<int>(to_int(f.val(), "collection.history_retention_hours"));
        else if (k == "whea_poll_seconds") cfg.collection.whea_poll_seconds = to_double(f.val(), "collection.whea_poll_seconds");
        else if (k == "top_others_poll_seconds") cfg.collection.top_others_poll_seconds = to_double(f.val(), "collection.top_others_poll_seconds");
        else warn(unk, "unknown key under 'collection': " + k);
    }
    if (cfg.collection.interval_seconds <= 0.0)
        throw RwConfigError("collection.interval_seconds must be > 0");
}

void parse_temps(ry::ConstNodeRef& n, RwConfig& cfg, std::vector<std::string>* unk) {
    for (auto f : n.children()) {
        auto k = str(f.key());
        if (k == "lhm_dll_path") cfg.temps.lhm_dll_path = str(f.val());
        else if (k == "cpu_sensor_name") cfg.temps.cpu_sensor_name = str(f.val());
        else if (k == "tctl_offset") cfg.temps.tctl_offset = to_double(f.val(), "temps.tctl_offset");
        else warn(unk, "unknown key under 'temps': " + k);
    }
}

void parse_fika(ry::ConstNodeRef& n, RwConfig& cfg, std::vector<std::string>* unk) {
    for (auto f : n.children()) {
        auto k = str(f.key());
        if (k == "spt_path") cfg.fika.spt_path = str(f.val());
        else if (k == "headless_path") cfg.fika.headless_path = str(f.val());
        else if (k == "raid_udp_port") cfg.fika.raid_udp_port = static_cast<int>(to_int(f.val(), "fika.raid_udp_port"));
        else if (k == "log_paths") {
            if (!f.is_map()) throw RwConfigError("fika.log_paths must be a mapping");
            for (auto lp : f.children()) cfg.fika.log_paths[str(lp.key())] = str(lp.val());
        } else if (k == "risky_mod_names") {
            if (!f.is_seq()) throw RwConfigError("fika.risky_mod_names must be a sequence");
            for (auto m : f.children()) cfg.fika.risky_mod_names.push_back(str(m.val()));
        } else {
            warn(unk, "unknown key under 'fika': " + k);
        }
    }
    if (cfg.fika.raid_udp_port < 1 || cfg.fika.raid_udp_port > 65535)
        throw RwConfigError("fika.raid_udp_port must be 1-65535");
}

void parse_gate(const std::string& id, ry::ConstNodeRef& n, RwConfig& cfg,
                std::vector<std::string>* unk) {
    GateCfg g;
    for (auto f : n.children()) {
        auto k = str(f.key());
        if (k == "enabled") g.enabled = to_bool(f.val(), "gate." + id + ".enabled");
        else if (k == "threshold") g.threshold = to_double(f.val(), "gate." + id + ".threshold");
        else if (k == "operator") g.op = str(f.val());
        else if (k == "duration_seconds") g.duration_seconds = to_double(f.val(), "gate." + id + ".duration_seconds");
        else if (k == "severity") g.severity = str(f.val());
        else if (k == "recommendation") g.recommendation = str(f.val());
        else if (k == "metric") g.metric = str(f.val());
        else warn(unk, "unknown key under gate '" + id + "': " + k);
    }
    // Validations (real config mistakes — hard errors, D4).
    if (!operator_is_valid(g.op))
        throw RwConfigError("gate '" + id + "' operator must be one of > < >= <= == !=, got '" + g.op + "'");
    std::string sev_l = g.severity;
    std::transform(sev_l.begin(), sev_l.end(), sev_l.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    if (!severity_is_valid(sev_l))
        throw RwConfigError("gate '" + id + "' severity must be one of low medium high, got '" + g.severity + "'");
    g.severity = sev_l;
    if (g.duration_seconds < 0.0)
        throw RwConfigError("gate '" + id + "' duration_seconds must be >= 0");
    cfg.gates[id] = g;
}

void parse_gates(ry::ConstNodeRef& n, RwConfig& cfg, std::vector<std::string>* unk) {
    for (auto g : n.children()) parse_gate(str(g.key()), g, cfg, unk);
}

}  // namespace

// ------------------------------------------------------------ load_config ---

RwConfig load_config(const std::string& config_path, const std::string& example_path,
                     std::vector<std::string>* unknown_keys_out) {
    // --- D23: first-run auto-generation ---
    if (!fs::exists(config_path)) {
        std::error_code ec;
        fs::create_directories(fs::path(config_path).parent_path(), ec);
        if (fs::exists(example_path)) {
            fs::copy_file(example_path, config_path, fs::copy_options::overwrite_existing, ec);
            if (ec) throw RwConfigError("auto-generate: copy failed: " + ec.message());
            std::fprintf(stderr, "[rw_config] auto-generated %s from %s\n",
                         config_path.c_str(), example_path.c_str());
        } else {
            std::ofstream out(config_path, std::ios::binary);
            if (!out) throw RwConfigError("auto-generate: cannot write " + config_path);
            out << dump_config_yaml(RwConfig{});
            std::fprintf(stderr, "[rw_config] auto-generated %s (no example present)\n",
                         config_path.c_str());
        }
    }

    // --- read + parse ---
    std::ifstream in(config_path, std::ios::binary);
    if (!in) throw RwConfigError("cannot read config: " + config_path);
    std::string buf((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());

    ry::Tree tree;
    try {
        tree = ry::parse_in_arena(ry::to_csubstr(buf));
    } catch (const std::exception& e) {
        throw RwConfigError(std::string("YAML parse error: ") + e.what());
    }

    RwConfig cfg;
    ry::ConstNodeRef root = tree.rootref();
    if (!root.is_map()) {
        // Empty / non-mapping document ⇒ safe defaults (config.py: raw == {}).
        return cfg;
    }

    for (auto sec : root.children()) {
        auto k = str(sec.key());
        if (k == "processes") { if (!sec.is_map()) throw RwConfigError("'processes' must be a mapping"); parse_processes(sec, cfg, unknown_keys_out); }
        else if (k == "collection") { if (!sec.is_map()) throw RwConfigError("'collection' must be a mapping"); parse_collection(sec, cfg, unknown_keys_out); }
        else if (k == "temps") { if (!sec.is_map()) throw RwConfigError("'temps' must be a mapping"); parse_temps(sec, cfg, unknown_keys_out); }
        else if (k == "fika") { if (!sec.is_map()) throw RwConfigError("'fika' must be a mapping"); parse_fika(sec, cfg, unknown_keys_out); }
        else if (k == "gates") { if (!sec.is_map()) throw RwConfigError("'gates' must be a mapping"); parse_gates(sec, cfg, unknown_keys_out); }
        else {
            // Dropped HTTP sections are silently tolerated too (warn, never fail).
            warn(unknown_keys_out, "unknown top-level key (ignored): " + k);
        }
    }
    return cfg;
}

}  // namespace raidwatch
